# Generated by Django 4.2.3 on 2023-07-21 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_finished', models.BooleanField(default=False)),
                ('status_code', models.CharField(max_length=255)),
                ('bad_url', models.BooleanField(default=False)),
                ('time_to_respond', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('timeout_res', models.BooleanField(default=False)),
                ('no_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
