# Generated by Django 4.2.3 on 2023-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_code',
            field=models.CharField(default='418', max_length=255),
        ),
    ]
