# Generated by Django 4.2.3 on 2023-07-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_url',
            field=models.URLField(default='no-url', max_length=2000),
        ),
    ]
