# Generated by Django 4.2.3 on 2023-07-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_task_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskThread',
        ),
        migrations.RemoveField(
            model_name='task',
            name='no_link',
        ),
    ]
