# Generated by Django 4.2.3 on 2023-07-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_taskthread_remove_task_no_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
